name = "要跑啊，少年"
license = "MIT"
licenselink = "https://github.com/reuixiy/hugo-theme-meme/blob/master/LICENSE"
description = "因为无人关注而特有的专注."
homepage = "https://github.com/reuixiy/hugo-theme-meme/"
tags = ["Blog", "Minimal", "Clean", "Typography", "Multilingual"]
features = ["Dark Mode", "MathJax", "KaTeX", "JSON-LD", "Drop Cap", "PWA", "TOC"]
min_version = "0.86.0"

[author]
name = "reuixiy"
homepage = "https://yaopao.xyz/"
